plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory: {}
  lookup:
    sops:
      description: Read sops encrypted file contents
      name: sops
      version_added: 0.1.0
  module:
    load_vars:
      description: Load sops-encrypted variables from files, dynamically within a
        task
      name: load_vars
      namespace: ''
      version_added: 0.1.0
    sops_encrypt:
      description: Encrypt data with sops
      name: sops_encrypt
      namespace: ''
      version_added: 0.1.0
  netconf: {}
  shell: {}
  strategy: {}
  vars:
    sops:
      description: Loading sops-encrypted vars files
      name: sops
      version_added: 0.1.0
version: 1.0.4
