add object.playbook:
  - name: install
    description: Installs sops and GNU Privacy Guard on all remote hosts
  - name: install_localhost
    description: Installs sops and GNU Privacy Guard on localhost
